name: Update README

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy docs/README.md to README.md
        run: cp docs/README.md README.md

      - name: Commit changes
        run: |
          git config --local user.email "vinulike11@gmail.com"
          git config --local user.name "vinugawade"
          git add README.md
          git commit -m "feat: update `README.md` with `docs/README.md` content" || true
          git push origin master
