name: "Vinu's DevCard"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.3.1
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}